chains-project/dirty-waters

tool/extract_deps.py, tool/main.py
Now "-pm pnpm" is used to extract all dependencies and "--pnpm-scope" can be used to extract dependencies from pnpm with a specific scope
=> Add feature to parse file pnpm-lock.yaml

.github/run-formatter.yml, .github/run-linter.yml, pyproject.toml
Formatter is Black, linter is Ruff
Open to suggestions for other formatters/linters
We should also include some kind of testing soon
Closes #10
=> feat: add formatter, linter to CI

pyproject.toml
=> feat: add project entry point for executable creation on install

tool/extract_deps.py, tool/github_repo.py, tool/main.py, tool/report_static.py, tool/static_analysis.py
Closed the previous PR because it was too cluttered, should be way easier to follow this one
Provenance and deprecation checks not currently supported
@Stamp9 I noticed that forks are only checked if no provenance was found, should this still be the case?
Closes #7
=> feat: add maven support

tool/report_static.py
=> fix: add provenance to execution report, remove irrelevant information from tables

tool/compare_commits.py
=> feat: add remaining tag format checks from AROMA paper

README.md
=> docs: add missing tag formats to README

requirements.txt, tool/extract_deps.py, tool/main.py
Closes #46 
Is working for StoyanTc/yammer-metrics - v3.0.1!
cc @algomaster99
=> fix: dependency parsing for child modules

flake.lock, flake.nix, pyproject.toml, requirements.txt
cc @algomaster99 thanks for the catch!
=> chore: pin GitPython version in requirements.txt

README.md, tool/compare_commits.py, tool/compare_packages.py, tool/main.py, tool/report_diff.py, tool/report_static.py
Relates to https://github.com/chains-project/dirty-waters-action/issues/3
Need opinion from @Stamp9  and @monperrus  before merging; note that this is just an option, and can easily be disabled
If merged, will need to be reflected in the action
=> feat: add gradual reporting by default

README.md, pyproject.toml, tool/compare_commits.py, tool/extract_deps.py, tool/get_pr_info.py, tool/get_pr_review.py, tool/get_user_commit_info.py, tool/github_repo.py, tool/main.py, tool/static_analysis.py
I'm running a few tests, if everything's fine I'll merge
Closes #66 
cc @monperrus
=> fix: packaging issues, modules not found on pip installation

README.md, tool/main.py
=> chore: simplify CLI usage

tool/compare_commits.py, tool/get_pr_info.py, tool/get_pr_review.py, tool/report_static.py, tool/static_analysis.py, tool/tool_config.py
...+ fix fields (not) showing up in NPM scenarios due to missing parentheses
Relates to #14
=> feat: batch API calls in tag acquiring, get_pr_info, get_pr_review

README.md, tool/main.py, tool/report_diff.py, tool/report_static.py, tool/static_analysis.py, tool/tool_config.py
Allows for users to set dependencies they want to ignore during the tool's checks.
Closes #98
=> feat: add config support

README.md, tests/expected_outputs/metamask_v11.10.0.md, tests/expected_outputs/spoon_v11.1.0.md, tool/extract_deps.py, tool/main.py, tool/report_diff.py, tool/report_static.py, tool/static_analysis.py, tool/tool_config.py
cc @ericcornelissen @monperrus 
Only supports NPM atm, will try and add support for pnpm, yarn classic, yarn berry ASAP
Closes #26 
Closes #98 
Closes #105 
Closes #95
=> feat: add support for aliased deps, report them

.github/workflows/run-tests.yml, README.md, tests/dirty_waters_test.py, tests/expected_outputs/metamask_v11.10.0.md, tests/expected_outputs/spoon_v11.1.0.md, tool/github_repo.py, tool/main.py, tool/report_static.py, tool/static_analysis.py
Closes #103 
Relates to #96 
Also adds regex support to config ignore cc @ericcornelissen
=> feat: check for commit SHA via gitHead, fallback to tag check if not present

tool/tool_config.py
Whenever cache schemas change, we drop the changed tables, and re-compute stuff related with them
Closes https://github.com/chains-project/dirty-waters-action/issues/24
=> feat: add cache schema versioning

README.md, tool/static_analysis.py
=> feat: add possibility to ignore packages w/ specific parents in config

README.md, tool/report_static.py
=> docs: add possible check names to report, README

tool/report_static.py
=> feat: link package names to registry URLs in reports
